CONFIG_ZMK_KEYBOARD_NAME="Gravity36"
CONFIG_BT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_USB=y

CONFIG_RGBLED_WIDGET=y                    # 内蔵RGB LEDウィジェットの有効化
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=n  # バッテリーやレイヤーごとの色表示が不要な場合はオフ

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_USB_LOGGING=n
