CONFIG_ZMK_KEYBOARD_NAME="Gravity36"
CONFIG_BT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_USB=y

CONFIG_ZMK_POINTING=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_USB_LOGGING=n

# ZMK StudioのRPC通信用スレッドのスタックサイズを拡張（デフォルトから大幅に引き上げ）
CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=4096

# 通信パケットバッファの拡張
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=128
CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=256
