# config/build.yaml
---
include:
  - board: seeeduino_xiao_ble//zmk
    shield: gravity36_xiao_left
    snippets: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble//zmk
    shield: gravity36_xiao_right
  - board: seeeduino_xiao_ble//zmk
    shield: settings_reset
