# config/build.yaml
---
include:
  - board: xiao_ble/nrf52840/zmk
    shield: gravity36_xiao_left
    snippets:
      - zmk-rgbled-widget
  - board: xiao_ble/nrf52840/zmk
    shield: gravity36_xiao_right
    snippets:
      - zmk-rgbled-widget
  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
