# config/build.yaml
---
include:
  - board: seeeduino_xiao_ble
    shield: gravity36_xiao_left
    snippets:
      - zmk-rgbled-widget
  - board: seeeduino_xiao_ble
    shield: gravity36_xiao_right
    snippets:
      - zmk-rgbled-widget
  - board: seeeduino_xiao_ble
    shield: settings_reset
