CONFIG_ZMK_KEYBOARD_NAME="Gravity36_L"
CONFIG_ZMK_BLE=y

CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# 内蔵RGB LEDウィジェットの有効化（最新仕様）
CONFIG_RGBLED_WIDGET=y

# Bluetoothプロファイルごとの色設定（最新仕様・ZMK_が必須）
CONFIG_RGBLED_WIDGET_BT_COLOR_1=4
CONFIG_RGBLED_WIDGET_BT_COLOR_2=2
CONFIG_RGBLED_WIDGET_BT_COLOR_3=1
