CONFIG_ZMK_KEYBOARD_NAME="Gravity36_L"
CONFIG_ZMK_BLE=y

CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
# 内蔵RGB LEDウィジェットを有効化
CONFIG_RGBLED_WIDGET=y

# Bluetoothプロファイル（接続先）ごとの色を定義
# 0:黒(消灯), 1:赤, 2:緑, 3:黄, 4:青, 5:マゼンタ, 6:シアン, 7:白
CONFIG_RGBLED_WIDGET/BT_COLOR_1=4  # 1台目：青 (Blue)
CONFIG_RGBLED_WIDGET/BT_COLOR_2=2  # 2台目：緑 (Green)
CONFIG_RGBLED_WIDGET/BT_COLOR_3=1  # 3台目：赤 (Red)
